### ISSUE TITLE
Changing childcare address details deletes address but not the flag.

### ISSUE THREAD

**Issue by Thomas-95IS** [InformedSolutions/OFS-MORE-Childminder-Website#124]
On a returned application whose childcare address (within personal details) is flagged, removing the childcare address (by declaring the home address to be where the children are looked after) deletes the record but not its associated flag. The result is a flag which can never be removed by the applicant.

**Comment by ricaduchateau** [comment]
Hi @Thomas-95IS,

As I mentioned earlier, flagged tasks are no longer locked out once they're updated. Perhaps this could help with this issue?

With kind regards,

Rica

**Comment by ricaduchateau** [comment]
Migrated to Trello
